---
# IONOS Deploy Now Konfiguration
setup:
  name: static
  type: static
  buildConfig:
    dist: /
    cmd: false
  routes:
    - path: api/kontakt
      directory: api
      handler: kontakt.js
      runtime: node:18 