---
# IONOS Deploy Now Konfiguration
distFolder: .
deploy:
  # Deploy-Hook für das Bauen des Projekts
  buildCmd: npm ci
  # Verzeichnis, in dem die statischen Dateien liegen
  fromDist: true
  output: .

# Umgebungsvariablen für IONOS Deploy Now
environment:
  RESEND_API_KEY: "{{secrets.RESEND_API_KEY}}"

# API-Routen von IONOS Deploy Now
apiRoutes:
  - path: /api
    directory: api
    handler: kontakt.js
    runtime: node:18
    environment:
      - RESEND_API_KEY