---
# IONOS Deploy Now Konfiguration
distFolder: .
deploy:
  # Deploy-Hook für das Bauen des Projekts
  buildCmd: npm ci
  # Verzeichnis, in dem die statischen Dateien liegen
  fromDist: true
  output: .

# API-Routen von IONOS Deploy Now
apiRoutes:
  - path: /api/kontakt
    directory: api
    handler: kontakt.js
    runtime: node:18
    installCmd: cd api && npm install
    # Umgebungsvariablen
    environment:
      NODE_ENV: production
      DEBUG: "true"
      
  - path: /api/test
    directory: api
    handler: test.js
    runtime: node:18
    installCmd: cd api && npm install
    environment:
      NODE_ENV: production 