---
# IONOS Deploy Now Konfiguration
distFolder: .
deploy:
  # Deploy-Hook für das Bauen des Projekts
  buildCmd: npm ci
  # Verzeichnis, in dem die statischen Dateien liegen
  fromDist: true
  output: .

# API-Routen von IONOS Deploy Now
apiRoutes:
  - path: /api/kontakt
    directory: api
    handler: kontakt.js
    runtime: node:18
    installCmd: npm install
    # Umgebungsvariablen falls nötig (optional)
    environment:
      NODE_ENV: production 