name: Deploy KANID Website

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup PHP 8.3
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
        extensions: mbstring, xml, ctype, iconv, intl, pdo, pdo_mysql
        coverage: none
    
    - name: Install Composer
      run: |
        curl -sS https://getcomposer.org/installer | php
        sudo mv composer.phar /usr/local/bin/composer
    
    - name: Install dependencies
      run: composer install --no-dev --prefer-dist --no-interaction
      env:
        RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup PHP 8.3
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
        extensions: mbstring, xml, ctype, iconv, intl, pdo, pdo_mysql
    
    - name: Install Composer
      run: |
        curl -sS https://getcomposer.org/installer | php
        sudo mv composer.phar /usr/local/bin/composer
    
    - name: Build project
      run: |
        composer install --no-dev --prefer-dist --no-interaction
        echo "Build erfolgreich abgeschlossen"
      env:
        RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
    
    - name: Deploy to IONOS
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.IONOS_HOST }}
        username: ${{ secrets.IONOS_USERNAME }}
        key: ${{ secrets.IONOS_SSH_KEY }}
        port: ${{ secrets.IONOS_PORT }}
        script: |
          cd /var/www/html/
          git pull origin main
          composer install --no-dev --prefer-dist --no-interaction
          chmod 644 .htaccess
          chmod 644 *.html
          chmod 644 assets/css/*.css
          chmod 644 assets/js/*.js
          echo "Deployment erfolgreich abgeschlossen"
