name: Deploy KANID Website

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup PHP 8.3
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
        extensions: mbstring, xml, ctype, iconv, intl, pdo, pdo_mysql
        coverage: none
    
    - name: Setup Composer
      uses: ramsey/composer-install@v4
      with:
        composer-options: '--no-dev --prefer-dist --no-interaction'
        dependency-versions: 'locked'
    
    - name: Validate composer.json
      run: composer validate --strict
    
    - name: Check for security vulnerabilities
      run: composer audit --format=json --output=security-report.json || true
    
    - name: Upload security report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: security-report
        path: security-report.json

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup PHP 8.3
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
        extensions: mbstring, xml, ctype, iconv, intl, pdo, pdo_mysql
    
    - name: Setup Composer
      uses: ramsey/composer-install@v4
      with:
        composer-options: '--no-dev --prefer-dist --no-interaction'
        dependency-versions: 'locked'
    
    - name: Build project
      run: |
        composer install --no-dev --prefer-dist --no-interaction
        echo "Build erfolgreich abgeschlossen"
    
    - name: Deploy to IONOS
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.IONOS_HOST }}
        username: ${{ secrets.IONOS_USERNAME }}
        key: ${{ secrets.IONOS_SSH_KEY }}
        port: ${{ secrets.IONOS_PORT }}
        script: |
          cd /var/www/html/
          git pull origin main
          composer install --no-dev --prefer-dist --no-interaction
          chmod 644 .htaccess
          chmod 644 *.html
          chmod 644 assets/css/*.css
          chmod 644 assets/js/*.js
          echo "Deployment erfolgreich abgeschlossen"
